"""Numerical helpers for Liouvillian non-Bloch geometry.

The first implementation uses a nonreciprocal SSH drift matrix as a clean
scaffold. Later iterations should add explicitly constructed jump operators
and covariance-matrix dynamics.
"""

from __future__ import annotations

from dataclasses import dataclass
import numpy as np


@dataclass(frozen=True)
class BosonicLindbladEmbedding:
    """First-moment embedding of a drift matrix in a bosonic Gaussian Lindblad model.

    For linear bosonic jump operators, the first moments obey

        d<a>/dt = X <a>,
        X = -i H + (Gamma_gain - Gamma_loss) / 2.

    Any finite matrix X can be split into its anti-Hermitian Hamiltonian part and
    Hermitian gain/loss part.  If X is stable, this gives a bona fide Gaussian
    Lindblad realization of the rapidity block, although the jump modes can be
    spatially extended.
    """

    hamiltonian: np.ndarray
    gain_matrix: np.ndarray
    loss_matrix: np.ndarray
    gain_rates: np.ndarray
    loss_rates: np.ndarray
    gain_modes: np.ndarray
    loss_modes: np.ndarray
    reconstruction_error: float


@dataclass(frozen=True)
class LocalBosonicHatanoParams:
    """Nearest-neighbor bosonic Lindblad realization of a Hatano-Nelson drift.

    The first moments obey

        d<a_j>/dt = -gamma a_j + t_right a_{j-1} + t_left a_{j+1}

    under a local active reservoir:

    - Hamiltonian hopping
      ``H_{j+1,j} = i (t_right - t_left) / 2`` and Hermitian conjugate.
    - Bond gain jumps ``sqrt(c) (a_j^dagger + a_{j+1}^dagger)``.
    - Bond loss jumps ``sqrt(c) (a_j - a_{j+1})``.
    - Onsite loss jumps ``sqrt(2 gamma) a_j``.

    Here ``c = (t_right + t_left) / 2``.  The symmetric bond gain/loss pair
    creates the Hermitian off-diagonal part of the rapidity block while
    cancelling diagonal bond damping exactly.
    """

    t_right: float = 1.0
    t_left: float = 0.25
    gamma: float = 1.2

    def __post_init__(self) -> None:
        if self.t_right < 0 or self.t_left < 0 or self.gamma < 0:
            raise ValueError("Rates must be nonnegative.")

    @property
    def bond_rate(self) -> float:
        return 0.5 * (self.t_right + self.t_left)

    @property
    def chiral_hopping(self) -> float:
        return 0.5 * (self.t_right - self.t_left)


def bosonic_lindblad_embedding_from_drift(
    x: np.ndarray,
    tol: float = 1e-12,
) -> BosonicLindbladEmbedding:
    """Return a CP bosonic Gaussian first-moment embedding of ``x``.

    The Hermitian part of ``x`` is decomposed spectrally as
    ``S = S_plus - S_minus``.  The positive part is interpreted as gain and the
    negative part as loss:

        Gamma_gain = 2 S_plus, Gamma_loss = 2 S_minus.

    The anti-Hermitian part is ``-i H`` with Hermitian ``H``.
    """

    x = np.asarray(x, dtype=complex)
    hermitian = 0.5 * (x + x.conj().T)
    anti = 0.5 * (x - x.conj().T)
    hamiltonian = 1j * anti
    hamiltonian = 0.5 * (hamiltonian + hamiltonian.conj().T)

    evals, modes = np.linalg.eigh(hermitian)
    gain_rates = 2.0 * np.clip(evals, 0.0, None)
    loss_rates = 2.0 * np.clip(-evals, 0.0, None)
    gain_matrix = (modes * gain_rates) @ modes.conj().T
    loss_matrix = (modes * loss_rates) @ modes.conj().T

    gain_rates = np.where(gain_rates > tol, gain_rates, 0.0)
    loss_rates = np.where(loss_rates > tol, loss_rates, 0.0)
    reconstructed = -1j * hamiltonian + 0.5 * (gain_matrix - loss_matrix)
    reconstruction_error = float(np.linalg.norm(reconstructed - x) / np.linalg.norm(x))

    return BosonicLindbladEmbedding(
        hamiltonian=hamiltonian,
        gain_matrix=gain_matrix,
        loss_matrix=loss_matrix,
        gain_rates=gain_rates,
        loss_rates=loss_rates,
        gain_modes=modes,
        loss_modes=modes,
        reconstruction_error=reconstruction_error,
    )


def local_bosonic_hatano_drift(
    n_sites: int,
    p: LocalBosonicHatanoParams = LocalBosonicHatanoParams(),
) -> np.ndarray:
    """Return the exact rapidity block generated by the local reservoir."""

    x = np.zeros((n_sites, n_sites), dtype=complex)
    np.fill_diagonal(x, -p.gamma)
    for j in range(n_sites - 1):
        x[j + 1, j] = p.t_right
        x[j, j + 1] = p.t_left
    return x


def local_bosonic_hatano_lindblad_matrices(
    n_sites: int,
    p: LocalBosonicHatanoParams = LocalBosonicHatanoParams(),
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return ``H, Gamma_gain, Gamma_loss`` for the local reservoir.

    The returned matrices satisfy

        X = -i H + (Gamma_gain - Gamma_loss) / 2.
    """

    h = np.zeros((n_sites, n_sites), dtype=complex)
    gamma_gain = np.zeros((n_sites, n_sites), dtype=complex)
    gamma_loss = 2.0 * p.gamma * np.eye(n_sites, dtype=complex)

    c = p.bond_rate
    v = p.chiral_hopping
    for j in range(n_sites - 1):
        h[j + 1, j] += 1j * v
        h[j, j + 1] += -1j * v

        plus = np.zeros((n_sites, 1), dtype=complex)
        plus[j, 0] = np.sqrt(c)
        plus[j + 1, 0] = np.sqrt(c)
        gamma_gain += plus @ plus.conj().T

        minus = np.zeros((n_sites, 1), dtype=complex)
        minus[j, 0] = np.sqrt(c)
        minus[j + 1, 0] = -np.sqrt(c)
        gamma_loss += minus @ minus.conj().T

    return h, gamma_gain, gamma_loss


def local_bosonic_hatano_reconstructed_drift(
    n_sites: int,
    p: LocalBosonicHatanoParams = LocalBosonicHatanoParams(),
) -> np.ndarray:
    """Return the drift reconstructed from local Lindblad matrices."""

    h, gamma_gain, gamma_loss = local_bosonic_hatano_lindblad_matrices(n_sites, p)
    return -1j * h + 0.5 * (gamma_gain - gamma_loss)


def local_bosonic_hatano_jump_summary(
    n_sites: int,
    p: LocalBosonicHatanoParams = LocalBosonicHatanoParams(),
) -> dict[str, float]:
    """Return compact counts and rates for the local jump construction."""

    return {
        "bond_gain_jumps": float(max(n_sites - 1, 0)),
        "bond_loss_jumps": float(max(n_sites - 1, 0)),
        "onsite_loss_jumps": float(n_sites),
        "bond_gain_rate": p.bond_rate,
        "bond_loss_rate": p.bond_rate,
        "onsite_loss_rate": 2.0 * p.gamma,
        "hamiltonian_chiral_hopping": p.chiral_hopping,
    }


def arnoldi_basis(
    matrix: np.ndarray,
    seed: np.ndarray,
    max_dim: int | None = None,
    tol: float = 1e-12,
) -> tuple[np.ndarray, np.ndarray]:
    """Return an orthonormal Arnoldi basis and projected Hessenberg matrix."""

    matrix = np.asarray(matrix, dtype=complex)
    seed = np.asarray(seed, dtype=complex)
    dim = matrix.shape[0] if max_dim is None else min(max_dim, matrix.shape[0])
    norm = np.linalg.norm(seed)
    if norm < tol:
        raise ValueError("Arnoldi seed has near-zero norm.")

    vectors = np.zeros((matrix.shape[0], dim), dtype=complex)
    hessenberg = np.zeros((dim, dim), dtype=complex)
    vectors[:, 0] = seed / norm
    actual_dim = dim

    for j in range(dim):
        w = matrix @ vectors[:, j]
        for i in range(j + 1):
            hessenberg[i, j] = np.vdot(vectors[:, i], w)
            w = w - hessenberg[i, j] * vectors[:, i]
        if j + 1 < dim:
            beta = np.linalg.norm(w)
            hessenberg[j + 1, j] = beta
            if beta < tol:
                actual_dim = j + 1
                break
            vectors[:, j + 1] = w / beta

    return vectors[:, :actual_dim], hessenberg[:actual_dim, :actual_dim]


def biorthogonal_krylov_basis(
    matrix: np.ndarray,
    right_seed: np.ndarray,
    left_seed: np.ndarray | None = None,
    max_dim: int | None = None,
    tol: float = 1e-10,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return two-sided Krylov bases with ``W.conj().T @ V ~= I``.

    This is a robust Gram-Schmidt implementation rather than a strict
    three-term Lanczos recurrence.  It is therefore slower but much less fragile
    near exceptional points and is good enough for diagnostics.
    """

    matrix = np.asarray(matrix, dtype=complex)
    right_seed = np.asarray(right_seed, dtype=complex)
    if left_seed is None:
        left_seed = right_seed.copy()
    else:
        left_seed = np.asarray(left_seed, dtype=complex)

    dim = matrix.shape[0] if max_dim is None else min(max_dim, matrix.shape[0])
    right_vectors: list[np.ndarray] = []
    left_vectors: list[np.ndarray] = []

    v = right_seed.astype(complex, copy=True)
    w = left_seed.astype(complex, copy=True)
    overlap = np.vdot(w, v)
    if abs(overlap) < tol:
        raise ValueError("Biorthogonal seeds have near-zero overlap.")
    scale = np.sqrt(overlap)
    v = v / scale
    w = w / scale.conjugate()
    right_vectors.append(v)
    left_vectors.append(w)

    for _ in range(1, dim):
        v = matrix @ right_vectors[-1]
        w = matrix.conj().T @ left_vectors[-1]

        if right_vectors:
            v_stack = np.column_stack(right_vectors)
            w_stack = np.column_stack(left_vectors)
            v = v - v_stack @ (w_stack.conj().T @ v)
            w = w - w_stack @ (v_stack.conj().T @ w)

            # A second pass improves biorthogonality for strongly non-normal
            # matrices without committing to fragile recurrence coefficients.
            v = v - v_stack @ (w_stack.conj().T @ v)
            w = w - w_stack @ (v_stack.conj().T @ w)

        overlap = np.vdot(w, v)
        if abs(overlap) < tol:
            break
        scale = np.sqrt(overlap)
        v = v / scale
        w = w / scale.conjugate()
        right_vectors.append(v)
        left_vectors.append(w)

    v_basis = np.column_stack(right_vectors)
    w_basis = np.column_stack(left_vectors)
    projected = w_basis.conj().T @ matrix @ v_basis
    return v_basis, w_basis, projected


def krylov_spread_from_coefficients(coefficients: np.ndarray) -> float:
    """Return the first moment of absolute Krylov weights."""

    weights = np.abs(coefficients) ** 2
    total = float(np.sum(weights))
    if total == 0.0:
        return 0.0
    return float(np.arange(len(weights), dtype=float) @ weights / total)


def orthogonal_krylov_spread(vectors: np.ndarray, state: np.ndarray) -> float:
    """Return Arnoldi-basis spread of ``state``."""

    coeffs = vectors.conj().T @ state
    return krylov_spread_from_coefficients(coeffs)


def biorthogonal_krylov_spread(
    left_vectors: np.ndarray,
    state: np.ndarray,
) -> float:
    """Return a two-sided Krylov spread using left basis coefficients."""

    coeffs = left_vectors.conj().T @ state
    return krylov_spread_from_coefficients(coeffs)


@dataclass(frozen=True)
class NonBlochSSHParams:
    """Parameters for the two-band nonreciprocal SSH drift matrix."""

    t1_r: float = 0.6
    t1_l: float = 1.2
    t2: float = 1.0
    kappa: float = 0.2

    @property
    def gbz_radius(self) -> float:
        if self.t1_r == 0:
            raise ValueError("t1_r must be nonzero for the analytic GBZ radius.")
        return float(np.sqrt(abs(self.t1_l / self.t1_r)))


def bloch_hamiltonian(beta: complex, p: NonBlochSSHParams) -> np.ndarray:
    """Return the nonreciprocal SSH Hamiltonian H(beta)."""

    return np.array(
        [
            [0.0, p.t1_r + p.t2 / beta],
            [p.t1_l + p.t2 * beta, 0.0],
        ],
        dtype=complex,
    )


def drift_matrix(beta: complex, p: NonBlochSSHParams) -> np.ndarray:
    """Return a Liouvillian single-particle drift matrix X(beta)."""

    return -p.kappa * np.eye(2, dtype=complex) - 1j * bloch_hamiltonian(beta, p)


def right_left_eigensystem(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return eigenvalues and biorthonormal right/left eigenvector matrices.

    Columns of R are right eigenvectors. Columns of L are left eigenvectors
    represented as kets, so L.conj().T @ R = I after normalization.
    """

    evals_r, rvecs = np.linalg.eig(matrix)
    # For a diagonalizable matrix, rows of inv(R) are the left eigenvectors.
    # This avoids fragile pair-by-pair normalization near non-Hermitian
    # self-orthogonality, which is common close to exceptional points.
    lvecs = np.linalg.inv(rvecs).conj().T

    return evals_r, rvecs, lvecs


def tracked_band_from_drift(
    matrix_fn,
    k_values: np.ndarray,
    band: str = "lower",
) -> tuple[list[np.ndarray], list[np.ndarray], list[complex]]:
    """Track a rapidity band continuously for a Bloch drift matrix function."""

    right: list[np.ndarray] = []
    left: list[np.ndarray] = []
    evals_out: list[complex] = []
    previous_r: np.ndarray | None = None
    previous_l: np.ndarray | None = None

    for i, k in enumerate(k_values):
        x = matrix_fn(float(k))
        evals, rvecs, lvecs = right_left_eigensystem(x)

        if i == 0:
            energy_like = 1j * evals
            order = np.argsort(energy_like.real)
            if band == "lower":
                idx = int(order[0])
            elif band == "upper":
                idx = int(order[-1])
            else:
                raise ValueError("band must be 'lower' or 'upper'.")
        else:
            assert previous_r is not None and previous_l is not None
            overlaps = []
            for j in range(rvecs.shape[1]):
                forward = np.vdot(previous_l, rvecs[:, j])
                backward = np.vdot(lvecs[:, j], previous_r)
                overlaps.append(abs(forward * backward))
            idx = int(np.argmax(overlaps))

        previous_r = rvecs[:, idx]
        previous_l = lvecs[:, idx]
        right.append(previous_r)
        left.append(previous_l)
        evals_out.append(complex(evals[idx]))

    return right, left, evals_out


def metric_density_from_tracked_vectors(
    right: list[np.ndarray],
    left: list[np.ndarray],
    dk: float,
) -> np.ndarray:
    """Gauge-invariant finite-difference metric density from tracked vectors."""

    densities = np.empty(len(right), dtype=float)
    for i in range(len(right)):
        j = (i + 1) % len(right)
        a = np.vdot(left[i], right[j])
        b = np.vdot(left[j], right[i])
        ds2 = 1.0 - a * b
        densities[i] = float(np.real(ds2) / (dk * dk))
    return densities


def metric_density_from_drift(
    matrix_fn,
    k_values: np.ndarray,
    band: str = "lower",
) -> np.ndarray:
    """Compute a tracked finite-difference metric density for a drift matrix."""

    right, left, _ = tracked_band_from_drift(matrix_fn, k_values, band=band)
    dk = float(k_values[1] - k_values[0])
    return metric_density_from_tracked_vectors(right, left, dk)


def finite_chain_projector_from_drift(
    x: np.ndarray,
    states_per_band: int,
    band: str = "lower",
) -> np.ndarray:
    """Build a biorthogonal finite-chain band projector from a drift matrix."""

    evals, rvecs, lvecs = right_left_eigensystem(x)
    energy_like = 1j * evals
    if band == "lower":
        selected = np.argsort(energy_like.real)[:states_per_band]
    elif band == "upper":
        selected = np.argsort(energy_like.real)[-states_per_band:]
    else:
        raise ValueError("band must be 'lower' or 'upper'.")

    projector = np.zeros_like(x)
    for idx in selected:
        r = rvecs[:, idx : idx + 1]
        l = lvecs[:, idx : idx + 1]
        projector += r @ l.conj().T
    return projector


def real_space_metric_from_projector(
    projector: np.ndarray,
    cells: int,
    orbitals_per_cell: int,
) -> float:
    """Return Re Tr[P x (1-P) x P] / L."""

    positions = np.repeat(np.arange(cells, dtype=float), orbitals_per_cell)
    x_op = np.diag(positions)
    identity = np.eye(orbitals_per_cell * cells, dtype=complex)
    q = identity - projector
    value = np.trace(projector @ x_op @ q @ x_op @ projector) / cells
    return float(np.real(value))


def band_index_from_energy(h: np.ndarray, band: str = "lower") -> int:
    """Choose a band index from the Hamiltonian eigenvalues by real energy."""

    evals, _ = np.linalg.eig(h)
    order = np.argsort(evals.real)
    if band == "lower":
        return int(order[0])
    if band == "upper":
        return int(order[-1])
    raise ValueError("band must be 'lower' or 'upper'.")


def biorthogonal_band_vectors(
    beta: complex,
    p: NonBlochSSHParams,
    band: str = "lower",
) -> tuple[complex, np.ndarray, np.ndarray]:
    """Return eigenvalue, right ket, and left ket for a chosen band."""

    x = drift_matrix(beta, p)
    evals, rvecs, lvecs = right_left_eigensystem(x)
    energy_like = 1j * (evals + p.kappa)
    order = np.argsort(energy_like.real)
    if band == "lower":
        idx = int(order[0])
    elif band == "upper":
        idx = int(order[-1])
    else:
        raise ValueError("band must be 'lower' or 'upper'.")
    return evals[idx], rvecs[:, idx], lvecs[:, idx]


def gbz_metric_density(
    p: NonBlochSSHParams,
    k_values: np.ndarray,
    band: str = "lower",
    radius: float | None = None,
) -> np.ndarray:
    """Gauge-invariant finite-difference metric density on a circular GBZ."""

    r = p.gbz_radius if radius is None else radius
    dk = float(k_values[1] - k_values[0])
    right, left = tracked_gbz_band(p, k_values, band=band, radius=r)
    return metric_density_from_tracked_vectors(right, left, dk)


def tracked_gbz_band(
    p: NonBlochSSHParams,
    k_values: np.ndarray,
    band: str = "lower",
    radius: float | None = None,
) -> tuple[list[np.ndarray], list[np.ndarray]]:
    """Track a GBZ band continuously by maximizing biorthogonal overlap."""

    r = p.gbz_radius if radius is None else radius
    right: list[np.ndarray] = []
    left: list[np.ndarray] = []
    previous_r: np.ndarray | None = None
    previous_l: np.ndarray | None = None

    for i, k in enumerate(k_values):
        beta = r * np.exp(1j * k)
        x = drift_matrix(beta, p)
        evals, rvecs, lvecs = right_left_eigensystem(x)

        if i == 0:
            energy_like = 1j * (evals + p.kappa)
            order = np.argsort(energy_like.real)
            if band == "lower":
                idx = int(order[0])
            elif band == "upper":
                idx = int(order[-1])
            else:
                raise ValueError("band must be 'lower' or 'upper'.")
        else:
            assert previous_r is not None and previous_l is not None
            overlaps = []
            for j in range(rvecs.shape[1]):
                forward = np.vdot(previous_l, rvecs[:, j])
                backward = np.vdot(lvecs[:, j], previous_r)
                overlaps.append(abs(forward * backward))
            idx = int(np.argmax(overlaps))

        previous_r = rvecs[:, idx]
        previous_l = lvecs[:, idx]
        right.append(previous_r)
        left.append(previous_l)

    return right, left


def gbz_integrated_metric(
    p: NonBlochSSHParams,
    nk: int = 1200,
    band: str = "lower",
    radius: float | None = None,
) -> float:
    """Return the average GBZ metric density over k."""

    k_values = np.linspace(0.0, 2.0 * np.pi, nk, endpoint=False)
    density = gbz_metric_density(p, k_values, band=band, radius=radius)
    return float(np.mean(density))


def open_chain_hamiltonian(p: NonBlochSSHParams, cells: int) -> np.ndarray:
    """Return an open-boundary nonreciprocal SSH matrix with A/B sublattices."""

    n = 2 * cells
    h = np.zeros((n, n), dtype=complex)

    def a(j: int) -> int:
        return 2 * j

    def b(j: int) -> int:
        return 2 * j + 1

    for j in range(cells):
        h[a(j), b(j)] = p.t1_r
        h[b(j), a(j)] = p.t1_l
        if j + 1 < cells:
            h[a(j + 1), b(j)] = p.t2
            h[b(j), a(j + 1)] = p.t2

    return h


def open_chain_drift(p: NonBlochSSHParams, cells: int) -> np.ndarray:
    """Return the open-boundary drift matrix."""

    return -p.kappa * np.eye(2 * cells, dtype=complex) - 1j * open_chain_hamiltonian(p, cells)


def open_boundary_projector(
    p: NonBlochSSHParams,
    cells: int,
    band: str = "lower",
) -> np.ndarray:
    """Build a biorthogonal OBC band projector from half of the rapidity modes."""

    x = open_chain_drift(p, cells)
    return finite_chain_projector_from_drift(x, states_per_band=cells, band=band)


def real_space_integrated_metric(
    p: NonBlochSSHParams,
    cells: int,
    band: str = "lower",
) -> float:
    """Return Re Tr[P x (1-P) x P] / L for an open chain."""

    projector = open_boundary_projector(p, cells=cells, band=band)
    return real_space_metric_from_projector(projector, cells=cells, orbitals_per_cell=2)


def skin_center_of_mass(p: NonBlochSSHParams, cells: int, mode: int = 0) -> float:
    """Return the center of mass of an OBC right eigenmode probability profile."""

    x = open_chain_drift(p, cells)
    evals, rvecs = np.linalg.eig(x)
    order = np.argsort(evals.real)
    vec = rvecs[:, order[mode]]
    weights = np.abs(vec) ** 2
    positions = np.repeat(np.arange(cells, dtype=float), 2)
    return float(np.sum(positions * weights) / np.sum(weights))


@dataclass(frozen=True)
class DissipativeChainParams:
    """Physical one-band Lindblad chain with coherent hopping and bond loss."""

    hopping: float = 1.0
    gamma: float = 1.2
    onsite_loss: float = 0.0


@dataclass(frozen=True)
class PhysicalSSHParams:
    """Two-sublattice SSH Lindblad chain with oriented bond-loss jumps.

    The physical ingredients are Hermitian SSH hopping plus jump operators

        L_intra,j = sqrt(gamma1) (source + i target)
        L_inter,j = sqrt(gamma2) (source + i target)

    on selected bonds. The orientation signs determine the source-target
    direction:

    - intra_orientation = +1: A_j -> B_j
    - intra_orientation = -1: B_j -> A_j
    - inter_orientation = +1: B_j -> A_{j+1}
    - inter_orientation = -1: A_{j+1} -> B_j
    """

    t1: float = 0.9
    t2: float = 0.35
    gamma1: float = 0.7
    gamma2: float = 0.0
    intra_orientation: int = -1
    inter_orientation: int = 1
    onsite_loss: float = 0.05

    def __post_init__(self) -> None:
        if self.intra_orientation not in (-1, 1):
            raise ValueError("intra_orientation must be +1 or -1.")
        if self.inter_orientation not in (-1, 1):
            raise ValueError("inter_orientation must be +1 or -1.")
        if self.gamma1 < 0 or self.gamma2 < 0 or self.onsite_loss < 0:
            raise ValueError("Dissipation rates must be nonnegative.")

    @property
    def bulk_loss_shift(self) -> float:
        return -0.5 * (self.onsite_loss + self.gamma1 + self.gamma2)

    @property
    def effective_hoppings(self) -> tuple[float, float, float, float]:
        """Return a, b, c, d for X = eta I - i [[0,a+b/beta],[c+d beta,0]]."""

        a = self.t1 + 0.5 * self.intra_orientation * self.gamma1
        c = self.t1 - 0.5 * self.intra_orientation * self.gamma1

        # The intercell bond is geometrically B_j -- A_{j+1}; this reverses
        # the sign relative to the AB Bloch matrix element.
        b = self.t2 - 0.5 * self.inter_orientation * self.gamma2
        d = self.t2 + 0.5 * self.inter_orientation * self.gamma2
        return a, b, c, d

    @property
    def gbz_radius(self) -> float:
        a, b, c, d = self.effective_hoppings
        denom = a * d
        if abs(denom) < 1e-14:
            raise ValueError("Cannot compute a circular GBZ radius with a*d = 0.")
        return float(np.sqrt(abs(b * c / denom)))


def dissipative_bond_drift(
    p: DissipativeChainParams,
    sites: int,
    periodic: bool = False,
) -> np.ndarray:
    """Return X = -i h - M/2 for L_j = sqrt(gamma) (c_j + i c_{j+1})."""

    h = np.zeros((sites, sites), dtype=complex)
    m = p.onsite_loss * np.eye(sites, dtype=complex)

    bonds = [(j, j + 1) for j in range(sites - 1)]
    if periodic and sites > 2:
        bonds.append((sites - 1, 0))

    for j, jp in bonds:
        h[j, jp] += p.hopping
        h[jp, j] += p.hopping

        ell = np.zeros((sites, 1), dtype=complex)
        ell[j, 0] = np.sqrt(p.gamma)
        ell[jp, 0] = 1j * np.sqrt(p.gamma)
        m += ell.conj() @ ell.T

    return -1j * h - 0.5 * m


def _add_oriented_jump(m: np.ndarray, source: int, target: int, gamma: float) -> None:
    """Add M_ij = l_i^* l_j for L = sqrt(gamma) (c_source + i c_target)."""

    if gamma == 0:
        return
    ell = np.zeros((m.shape[0], 1), dtype=complex)
    ell[source, 0] = np.sqrt(gamma)
    ell[target, 0] = 1j * np.sqrt(gamma)
    m += ell.conj() @ ell.T


def physical_ssh_open_drift(p: PhysicalSSHParams, cells: int) -> np.ndarray:
    """Return the OBC drift matrix of the physical SSH Lindblad model."""

    n = 2 * cells
    h = np.zeros((n, n), dtype=complex)
    m = p.onsite_loss * np.eye(n, dtype=complex)

    def a(j: int) -> int:
        return 2 * j

    def b(j: int) -> int:
        return 2 * j + 1

    for j in range(cells):
        h[a(j), b(j)] += p.t1
        h[b(j), a(j)] += p.t1
        if p.intra_orientation == 1:
            _add_oriented_jump(m, a(j), b(j), p.gamma1)
        else:
            _add_oriented_jump(m, b(j), a(j), p.gamma1)

        if j + 1 < cells:
            h[b(j), a(j + 1)] += p.t2
            h[a(j + 1), b(j)] += p.t2
            if p.inter_orientation == 1:
                _add_oriented_jump(m, b(j), a(j + 1), p.gamma2)
            else:
                _add_oriented_jump(m, a(j + 1), b(j), p.gamma2)

    return -1j * h - 0.5 * m


def physical_ssh_bloch_drift(beta: complex, p: PhysicalSSHParams) -> np.ndarray:
    """Return the bulk Bloch drift matrix for the physical SSH Lindblad model."""

    a, b, c, d = p.effective_hoppings
    offdiag = np.array(
        [
            [0.0, a + b / beta],
            [c + d * beta, 0.0],
        ],
        dtype=complex,
    )
    return p.bulk_loss_shift * np.eye(2, dtype=complex) - 1j * offdiag


def physical_ssh_gbz_metric_density(
    p: PhysicalSSHParams,
    k_values: np.ndarray,
    band: str = "lower",
    radius: float | None = None,
) -> np.ndarray:
    """Return the physical SSH Liouvillian GBZ metric density."""

    r = p.gbz_radius if radius is None else radius

    def matrix_fn(k: float) -> np.ndarray:
        beta = r * np.exp(1j * k)
        return physical_ssh_bloch_drift(beta, p)

    return metric_density_from_drift(matrix_fn, k_values, band=band)


def physical_ssh_gbz_integrated_metric(
    p: PhysicalSSHParams,
    nk: int = 1200,
    band: str = "lower",
    radius: float | None = None,
) -> float:
    """Return average physical SSH Liouvillian GBZ metric density."""

    k_values = np.linspace(0.0, 2.0 * np.pi, nk, endpoint=False)
    density = physical_ssh_gbz_metric_density(p, k_values, band=band, radius=radius)
    return float(np.mean(density))


def physical_ssh_real_space_metric(
    p: PhysicalSSHParams,
    cells: int,
    band: str = "lower",
) -> float:
    """Return OBC real-space metric for the physical SSH Lindblad model."""

    x = physical_ssh_open_drift(p, cells)
    projector = finite_chain_projector_from_drift(x, states_per_band=cells, band=band)
    return real_space_metric_from_projector(projector, cells=cells, orbitals_per_cell=2)


def evolve_linear_drift(
    x: np.ndarray,
    initial: np.ndarray,
    times: np.ndarray,
) -> np.ndarray:
    """Evolve d psi / dt = X psi by diagonalization."""

    evals, rvecs = np.linalg.eig(x)
    inv_r = np.linalg.inv(rvecs)
    coeffs = inv_r @ initial
    states = []
    for time in times:
        states.append(rvecs @ (np.exp(evals * time) * coeffs))
    return np.asarray(states)


def normalized_profile_centers(states: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return norm and normalized center of mass for time-dependent profiles."""

    weights = np.abs(states) ** 2
    norms = np.sum(weights, axis=1)
    positions = np.arange(states.shape[1], dtype=float)
    centers = (weights @ positions) / np.maximum(norms, 1e-300)
    return norms, centers


def cell_resolved_norm(states: np.ndarray) -> np.ndarray:
    """Convert site-resolved two-sublattice weights to unit-cell weights."""

    weights = np.abs(states) ** 2
    return weights.reshape(weights.shape[0], -1, 2).sum(axis=2)


def cell_profile_observables(states: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return norm, cell COM, and left/right asymmetry for two-sublattice states."""

    cell_weights = cell_resolved_norm(states)
    norms = np.sum(cell_weights, axis=1)
    cells = cell_weights.shape[1]
    positions = np.arange(cells, dtype=float)
    centers = (cell_weights @ positions) / np.maximum(norms, 1e-300)
    center = cells // 2
    left = cell_weights[:, :center].sum(axis=1)
    right = cell_weights[:, center + 1 :].sum(axis=1)
    asymmetry = (right - left) / np.maximum(right + left, 1e-300)
    return norms, centers, asymmetry
